services:
  postgres:
    image: postgres:16
    container_name: people_postgres
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./warehouse/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U people -d people"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./apps/api
    container_name: people_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  airflow:
    build: ./infra/airflow
    container_name: people_airflow
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./infra/airflow/dags:/opt/airflow/dags
      - ./pipelines:/opt/airflow/pipelines
      - ./dbt/people_dbt:/opt/airflow/dbt/people_dbt

volumes:
  pgdata:
